// GENERATED by scripts/build-demo-assets.mjs — do not edit by hand.
// Re-run `node scripts/build-demo-assets.mjs` after changing DEMO PHOTOS/.
import type { CameraModeName } from '@/types/session'

export interface DemoPhoto {
  id: string
  src: string            // raw photo (public path); filtered at runtime via processSession
  w: number
  h: number
  mode: CameraModeName
  status: 'active' | 'flagged' | 'hidden'
  sigSrc: string | null  // pre-composited transparent signature annotation, if any
  memoryNumber: number
  capturedAt: string     // ISO
}

export const DEMO_PHOTOS: DemoPhoto[] = [
  {
    "id": "d01",
    "src": "/demo-media/photos/d01.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "flagged",
    "sigSrc": null,
    "memoryNumber": 1,
    "capturedAt": "2026-09-20T01:30:00.000Z"
  },
  {
    "id": "p01",
    "src": "/demo-media/photos/p01.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "flagged",
    "sigSrc": null,
    "memoryNumber": 2,
    "capturedAt": "2026-09-20T01:34:00.000Z"
  },
  {
    "id": "s01",
    "src": "/demo-media/photos/s01.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 3,
    "capturedAt": "2026-09-20T01:38:00.000Z"
  },
  {
    "id": "d02",
    "src": "/demo-media/photos/d02.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "hidden",
    "sigSrc": null,
    "memoryNumber": 4,
    "capturedAt": "2026-09-20T01:42:00.000Z"
  },
  {
    "id": "p02",
    "src": "/demo-media/photos/p02.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": "/demo-media/photos/p02.sig.png",
    "memoryNumber": 5,
    "capturedAt": "2026-09-20T01:46:00.000Z"
  },
  {
    "id": "s02",
    "src": "/demo-media/photos/s02.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 6,
    "capturedAt": "2026-09-20T01:50:00.000Z"
  },
  {
    "id": "d03",
    "src": "/demo-media/photos/d03.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 7,
    "capturedAt": "2026-09-20T01:54:00.000Z"
  },
  {
    "id": "p03",
    "src": "/demo-media/photos/p03.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": "/demo-media/photos/p03.sig.png",
    "memoryNumber": 8,
    "capturedAt": "2026-09-20T01:58:00.000Z"
  },
  {
    "id": "s03",
    "src": "/demo-media/photos/s03.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 9,
    "capturedAt": "2026-09-20T02:02:00.000Z"
  },
  {
    "id": "d04",
    "src": "/demo-media/photos/d04.jpg",
    "w": 1600,
    "h": 2400,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 10,
    "capturedAt": "2026-09-20T02:06:00.000Z"
  },
  {
    "id": "p04",
    "src": "/demo-media/photos/p04.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 11,
    "capturedAt": "2026-09-20T02:10:00.000Z"
  },
  {
    "id": "s04",
    "src": "/demo-media/photos/s04.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 12,
    "capturedAt": "2026-09-20T02:14:00.000Z"
  },
  {
    "id": "d05",
    "src": "/demo-media/photos/d05.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 13,
    "capturedAt": "2026-09-20T02:18:00.000Z"
  },
  {
    "id": "p05",
    "src": "/demo-media/photos/p05.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": "/demo-media/photos/p05.sig.png",
    "memoryNumber": 14,
    "capturedAt": "2026-09-20T02:22:00.000Z"
  },
  {
    "id": "s05",
    "src": "/demo-media/photos/s05.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 15,
    "capturedAt": "2026-09-20T02:26:00.000Z"
  },
  {
    "id": "d06",
    "src": "/demo-media/photos/d06.jpg",
    "w": 1600,
    "h": 2400,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 16,
    "capturedAt": "2026-09-20T02:30:00.000Z"
  },
  {
    "id": "p06",
    "src": "/demo-media/photos/p06.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": "/demo-media/photos/p06.sig.png",
    "memoryNumber": 17,
    "capturedAt": "2026-09-20T02:34:00.000Z"
  },
  {
    "id": "s06",
    "src": "/demo-media/photos/s06.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 18,
    "capturedAt": "2026-09-20T02:38:00.000Z"
  },
  {
    "id": "d07",
    "src": "/demo-media/photos/d07.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 19,
    "capturedAt": "2026-09-20T02:42:00.000Z"
  },
  {
    "id": "p07",
    "src": "/demo-media/photos/p07.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 20,
    "capturedAt": "2026-09-20T02:46:00.000Z"
  },
  {
    "id": "s07",
    "src": "/demo-media/photos/s07.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 21,
    "capturedAt": "2026-09-20T02:50:00.000Z"
  },
  {
    "id": "d08",
    "src": "/demo-media/photos/d08.jpg",
    "w": 1600,
    "h": 2400,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 22,
    "capturedAt": "2026-09-20T02:54:00.000Z"
  },
  {
    "id": "p08",
    "src": "/demo-media/photos/p08.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": "/demo-media/photos/p08.sig.png",
    "memoryNumber": 23,
    "capturedAt": "2026-09-20T02:58:00.000Z"
  },
  {
    "id": "s08",
    "src": "/demo-media/photos/s08.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 24,
    "capturedAt": "2026-09-20T03:02:00.000Z"
  },
  {
    "id": "d09",
    "src": "/demo-media/photos/d09.jpg",
    "w": 1600,
    "h": 2400,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 25,
    "capturedAt": "2026-09-20T03:06:00.000Z"
  },
  {
    "id": "p09",
    "src": "/demo-media/photos/p09.jpg",
    "w": 2400,
    "h": 2400,
    "mode": "polaroid",
    "status": "active",
    "sigSrc": "/demo-media/photos/p09.sig.png",
    "memoryNumber": 26,
    "capturedAt": "2026-09-20T03:10:00.000Z"
  },
  {
    "id": "s09",
    "src": "/demo-media/photos/s09.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 27,
    "capturedAt": "2026-09-20T03:14:00.000Z"
  },
  {
    "id": "d10",
    "src": "/demo-media/photos/d10.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 28,
    "capturedAt": "2026-09-20T03:18:00.000Z"
  },
  {
    "id": "s10",
    "src": "/demo-media/photos/s10.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 29,
    "capturedAt": "2026-09-20T03:22:00.000Z"
  },
  {
    "id": "d11",
    "src": "/demo-media/photos/d11.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 30,
    "capturedAt": "2026-09-20T03:26:00.000Z"
  },
  {
    "id": "s11",
    "src": "/demo-media/photos/s11.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 31,
    "capturedAt": "2026-09-20T03:30:00.000Z"
  },
  {
    "id": "d12",
    "src": "/demo-media/photos/d12.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 32,
    "capturedAt": "2026-09-20T03:34:00.000Z"
  },
  {
    "id": "s12",
    "src": "/demo-media/photos/s12.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 33,
    "capturedAt": "2026-09-20T03:38:00.000Z"
  },
  {
    "id": "d13",
    "src": "/demo-media/photos/d13.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 34,
    "capturedAt": "2026-09-20T03:42:00.000Z"
  },
  {
    "id": "s13",
    "src": "/demo-media/photos/s13.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 35,
    "capturedAt": "2026-09-20T03:46:00.000Z"
  },
  {
    "id": "d14",
    "src": "/demo-media/photos/d14.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 36,
    "capturedAt": "2026-09-20T03:50:00.000Z"
  },
  {
    "id": "s14",
    "src": "/demo-media/photos/s14.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 37,
    "capturedAt": "2026-09-20T03:54:00.000Z"
  },
  {
    "id": "d15",
    "src": "/demo-media/photos/d15.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 38,
    "capturedAt": "2026-09-20T03:58:00.000Z"
  },
  {
    "id": "s15",
    "src": "/demo-media/photos/s15.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 39,
    "capturedAt": "2026-09-20T04:02:00.000Z"
  },
  {
    "id": "d16",
    "src": "/demo-media/photos/d16.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 40,
    "capturedAt": "2026-09-20T04:06:00.000Z"
  },
  {
    "id": "s16",
    "src": "/demo-media/photos/s16.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 41,
    "capturedAt": "2026-09-20T04:10:00.000Z"
  },
  {
    "id": "d17",
    "src": "/demo-media/photos/d17.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 42,
    "capturedAt": "2026-09-20T04:14:00.000Z"
  },
  {
    "id": "s17",
    "src": "/demo-media/photos/s17.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 43,
    "capturedAt": "2026-09-20T04:18:00.000Z"
  },
  {
    "id": "d18",
    "src": "/demo-media/photos/d18.jpg",
    "w": 2400,
    "h": 1600,
    "mode": "disposable",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 44,
    "capturedAt": "2026-09-20T04:22:00.000Z"
  },
  {
    "id": "s18",
    "src": "/demo-media/photos/s18.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 45,
    "capturedAt": "2026-09-20T04:26:00.000Z"
  },
  {
    "id": "s19",
    "src": "/demo-media/photos/s19.jpg",
    "w": 2400,
    "h": 1800,
    "mode": "super8",
    "status": "active",
    "sigSrc": null,
    "memoryNumber": 46,
    "capturedAt": "2026-09-20T04:30:00.000Z"
  }
]
